/* GObject - GLib Type, Object, Parameter and Signal Library
 * Copyright (C) 1998-1999, 2000-2001 Tim Janik and Red Hat, Inc.
 *
 * SPDX-License-Identifier: LGPL-2.1-or-later
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, see <http://www.gnu.org/licenses/>.
 */

#ifndef __GOBJECT_VISIBILITY_H__
#define __GOBJECT_VISIBILITY_H__

#if !defined (__GLIB_GOBJECT_H_INSIDE__) && !defined (GOBJECT_COMPILATION)
#error "Only <glib-object.h> can be included directly."
#endif

/* Symbol visibility and export macros for WASM */

/* For WASM builds, we don't need complex visibility controls */
#ifdef GLIB_STATIC_COMPILATION
#define GOBJECT_AVAILABLE_IN_ALL
#define GOBJECT_AVAILABLE_IN_2_26
#define GOBJECT_AVAILABLE_IN_2_28
#define GOBJECT_AVAILABLE_IN_2_30
#define GOBJECT_AVAILABLE_IN_2_32
#define GOBJECT_AVAILABLE_IN_2_34
#define GOBJECT_AVAILABLE_IN_2_36
#define GOBJECT_AVAILABLE_IN_2_38
#define GOBJECT_AVAILABLE_IN_2_40
#define GOBJECT_AVAILABLE_IN_2_42
#define GOBJECT_AVAILABLE_IN_2_44
#define GOBJECT_AVAILABLE_IN_2_46
#define GOBJECT_AVAILABLE_IN_2_48
#define GOBJECT_AVAILABLE_IN_2_50
#define GOBJECT_AVAILABLE_IN_2_52
#define GOBJECT_AVAILABLE_IN_2_54
#define GOBJECT_AVAILABLE_IN_2_56
#define GOBJECT_AVAILABLE_IN_2_58
#define GOBJECT_AVAILABLE_IN_2_60
#define GOBJECT_AVAILABLE_IN_2_62
#define GOBJECT_AVAILABLE_IN_2_64
#define GOBJECT_AVAILABLE_IN_2_66
#define GOBJECT_AVAILABLE_IN_2_68
#define GOBJECT_AVAILABLE_IN_2_70
#define GOBJECT_AVAILABLE_IN_2_72
#define GOBJECT_AVAILABLE_IN_2_74
#define GOBJECT_AVAILABLE_IN_2_76
#define GOBJECT_AVAILABLE_IN_2_78
#define GOBJECT_AVAILABLE_IN_2_80
#define GOBJECT_AVAILABLE_IN_2_82
#define GOBJECT_AVAILABLE_IN_2_84
#define GOBJECT_AVAILABLE_IN_2_86

/* Type-specific availability macros */
#define GOBJECT_AVAILABLE_TYPE_IN_2_78
#define GOBJECT_AVAILABLE_TYPE_IN_2_80
#define GOBJECT_AVAILABLE_TYPE_IN_2_82
#define GOBJECT_AVAILABLE_TYPE_IN_2_84
#define GOBJECT_AVAILABLE_TYPE_IN_2_86
#endif

/* WASM build deprecation handling - simplified for static compilation */
#ifdef GLIB_STATIC_COMPILATION
#define GOBJECT_DEPRECATED
#define GOBJECT_DEPRECATED_FOR(f)
#define GOBJECT_DEPRECATED_MACRO
#define GOBJECT_DEPRECATED_MACRO_FOR(f)
#define GOBJECT_DEPRECATED_ENUMERATOR
#define GOBJECT_DEPRECATED_ENUMERATOR_FOR(f)
#define GOBJECT_DEPRECATED_TYPE
#define GOBJECT_DEPRECATED_TYPE_FOR(f)

/* Version-specific deprecation macros - need proper function attributes */
#define GOBJECT_DEPRECATED_IN_2_26
#define GOBJECT_DEPRECATED_IN_2_28
#define GOBJECT_DEPRECATED_IN_2_30
#define GOBJECT_DEPRECATED_IN_2_32
#define GOBJECT_DEPRECATED_IN_2_32_FOR(f)
#define GOBJECT_DEPRECATED_IN_2_34
#define GOBJECT_DEPRECATED_IN_2_36
#define GOBJECT_DEPRECATED_IN_2_38
#define GOBJECT_DEPRECATED_IN_2_40
#define GOBJECT_DEPRECATED_IN_2_42
#define GOBJECT_DEPRECATED_IN_2_44
#define GOBJECT_DEPRECATED_IN_2_46
#define GOBJECT_DEPRECATED_IN_2_48
#define GOBJECT_DEPRECATED_IN_2_50
#define GOBJECT_DEPRECATED_IN_2_52
#define GOBJECT_DEPRECATED_IN_2_54
#define GOBJECT_DEPRECATED_IN_2_56
#define GOBJECT_DEPRECATED_IN_2_58
#define GOBJECT_DEPRECATED_IN_2_60
#define GOBJECT_DEPRECATED_IN_2_62
#define GOBJECT_DEPRECATED_IN_2_64
#define GOBJECT_DEPRECATED_IN_2_66
#define GOBJECT_DEPRECATED_IN_2_68
#define GOBJECT_DEPRECATED_IN_2_70
#define GOBJECT_DEPRECATED_IN_2_72
#define GOBJECT_DEPRECATED_IN_2_74
#define GOBJECT_DEPRECATED_IN_2_76
#define GOBJECT_DEPRECATED_IN_2_78
#define GOBJECT_DEPRECATED_IN_2_80
#define GOBJECT_DEPRECATED_IN_2_82
#define GOBJECT_DEPRECATED_IN_2_84
#define GOBJECT_DEPRECATED_IN_2_86

/* Version-specific type deprecation macros */
#define GOBJECT_DEPRECATED_TYPE_IN_2_26
#define GOBJECT_DEPRECATED_TYPE_IN_2_28
#define GOBJECT_DEPRECATED_TYPE_IN_2_30
#define GOBJECT_DEPRECATED_TYPE_IN_2_32
#define GOBJECT_DEPRECATED_TYPE_IN_2_34
#define GOBJECT_DEPRECATED_TYPE_IN_2_36
#define GOBJECT_DEPRECATED_TYPE_IN_2_38
#define GOBJECT_DEPRECATED_TYPE_IN_2_40
#define GOBJECT_DEPRECATED_TYPE_IN_2_42
#define GOBJECT_DEPRECATED_TYPE_IN_2_44
#define GOBJECT_DEPRECATED_TYPE_IN_2_46
#define GOBJECT_DEPRECATED_TYPE_IN_2_48
#define GOBJECT_DEPRECATED_TYPE_IN_2_50
#define GOBJECT_DEPRECATED_TYPE_IN_2_52
#define GOBJECT_DEPRECATED_TYPE_IN_2_54
#define GOBJECT_DEPRECATED_TYPE_IN_2_56
#define GOBJECT_DEPRECATED_TYPE_IN_2_58
#define GOBJECT_DEPRECATED_TYPE_IN_2_60
#define GOBJECT_DEPRECATED_TYPE_IN_2_62
#define GOBJECT_DEPRECATED_TYPE_IN_2_64
#define GOBJECT_DEPRECATED_TYPE_IN_2_66
#define GOBJECT_DEPRECATED_TYPE_IN_2_68
#define GOBJECT_DEPRECATED_TYPE_IN_2_70
#define GOBJECT_DEPRECATED_TYPE_IN_2_72
#define GOBJECT_DEPRECATED_TYPE_IN_2_74
#define GOBJECT_DEPRECATED_TYPE_IN_2_76
#define GOBJECT_DEPRECATED_TYPE_IN_2_78
#define GOBJECT_DEPRECATED_TYPE_IN_2_80
#define GOBJECT_DEPRECATED_TYPE_IN_2_82
#define GOBJECT_DEPRECATED_TYPE_IN_2_84
#define GOBJECT_DEPRECATED_TYPE_IN_2_86

/* Enumeration-specific availability and deprecation macros */
#define GOBJECT_AVAILABLE_ENUMERATOR_IN_2_70
#define GOBJECT_AVAILABLE_ENUMERATOR_IN_2_72
#define GOBJECT_AVAILABLE_ENUMERATOR_IN_2_74
#define GOBJECT_AVAILABLE_ENUMERATOR_IN_2_76
#define GOBJECT_AVAILABLE_ENUMERATOR_IN_2_78
#define GOBJECT_AVAILABLE_ENUMERATOR_IN_2_80
#define GOBJECT_AVAILABLE_ENUMERATOR_IN_2_82
#define GOBJECT_AVAILABLE_ENUMERATOR_IN_2_84
#define GOBJECT_AVAILABLE_ENUMERATOR_IN_2_86

/* Additional specific deprecation macros with _FOR variants */
#define GOBJECT_DEPRECATED_ENUMERATOR_IN_2_26
#define GOBJECT_DEPRECATED_ENUMERATOR_IN_2_32_FOR(f)
#define GOBJECT_DEPRECATED_IN_2_32_FOR(f)
#define GOBJECT_DEPRECATED_IN_2_36_FOR(f)
#define GOBJECT_DEPRECATED_IN_2_40_FOR(f)
#define GOBJECT_DEPRECATED_IN_2_44_FOR(f)
#define GOBJECT_DEPRECATED_IN_2_46_FOR(f)
#define GOBJECT_DEPRECATED_IN_2_48_FOR(f)
#define GOBJECT_DEPRECATED_IN_2_50_FOR(f)
#define GOBJECT_DEPRECATED_IN_2_52_FOR(f)
#define GOBJECT_DEPRECATED_IN_2_54_FOR(f)
#define GOBJECT_DEPRECATED_IN_2_56_FOR(f)
#define GOBJECT_DEPRECATED_IN_2_58_FOR(f)
#define GOBJECT_DEPRECATED_IN_2_60_FOR(f)
#define GOBJECT_DEPRECATED_IN_2_62_FOR(f)
#define GOBJECT_DEPRECATED_IN_2_64_FOR(f)
#define GOBJECT_DEPRECATED_IN_2_66_FOR(f)
#define GOBJECT_DEPRECATED_IN_2_68_FOR(f)
#define GOBJECT_DEPRECATED_IN_2_70_FOR(f)
#define GOBJECT_DEPRECATED_IN_2_72_FOR(f)
#define GOBJECT_DEPRECATED_IN_2_74_FOR(f)
#define GOBJECT_DEPRECATED_IN_2_76_FOR(f)
#define GOBJECT_DEPRECATED_IN_2_78_FOR(f)
#define GOBJECT_DEPRECATED_IN_2_80_FOR(f)
#define GOBJECT_DEPRECATED_IN_2_82_FOR(f)
#define GOBJECT_DEPRECATED_IN_2_84_FOR(f)
#define GOBJECT_DEPRECATED_IN_2_86_FOR(f)

/* Macro availability markers - empty for WASM build */
#define GOBJECT_AVAILABLE_MACRO_IN_2_26
#define GOBJECT_AVAILABLE_MACRO_IN_2_28
#define GOBJECT_AVAILABLE_MACRO_IN_2_30
#define GOBJECT_AVAILABLE_MACRO_IN_2_32
#define GOBJECT_AVAILABLE_MACRO_IN_2_34
#define GOBJECT_AVAILABLE_MACRO_IN_2_36
#define GOBJECT_AVAILABLE_MACRO_IN_2_38
#define GOBJECT_AVAILABLE_MACRO_IN_2_40
#define GOBJECT_AVAILABLE_MACRO_IN_2_42
#define GOBJECT_AVAILABLE_MACRO_IN_2_44
#define GOBJECT_AVAILABLE_MACRO_IN_2_46
#define GOBJECT_AVAILABLE_MACRO_IN_2_48
#define GOBJECT_AVAILABLE_MACRO_IN_2_50
#define GOBJECT_AVAILABLE_MACRO_IN_2_52
#define GOBJECT_AVAILABLE_MACRO_IN_2_54
#define GOBJECT_AVAILABLE_MACRO_IN_2_56
#define GOBJECT_AVAILABLE_MACRO_IN_2_58
#define GOBJECT_AVAILABLE_MACRO_IN_2_60
#define GOBJECT_AVAILABLE_MACRO_IN_2_62
#define GOBJECT_AVAILABLE_MACRO_IN_2_64
#define GOBJECT_AVAILABLE_MACRO_IN_2_66
#define GOBJECT_AVAILABLE_MACRO_IN_2_68
#define GOBJECT_AVAILABLE_MACRO_IN_2_70
#define GOBJECT_AVAILABLE_MACRO_IN_2_72
#define GOBJECT_AVAILABLE_MACRO_IN_2_74
#define GOBJECT_AVAILABLE_MACRO_IN_2_76
#define GOBJECT_AVAILABLE_MACRO_IN_2_78
#define GOBJECT_AVAILABLE_MACRO_IN_2_80
#define GOBJECT_AVAILABLE_MACRO_IN_2_82
#define GOBJECT_AVAILABLE_MACRO_IN_2_84
#define GOBJECT_AVAILABLE_MACRO_IN_2_86

/* Deprecated macro markers - empty for WASM build */
#define GOBJECT_DEPRECATED_MACRO_IN_2_26
#define GOBJECT_DEPRECATED_MACRO_IN_2_28
#define GOBJECT_DEPRECATED_MACRO_IN_2_30
#define GOBJECT_DEPRECATED_MACRO_IN_2_32
#define GOBJECT_DEPRECATED_MACRO_IN_2_34
#define GOBJECT_DEPRECATED_MACRO_IN_2_36
#define GOBJECT_DEPRECATED_MACRO_IN_2_38
#define GOBJECT_DEPRECATED_MACRO_IN_2_40
#define GOBJECT_DEPRECATED_MACRO_IN_2_42
#define GOBJECT_DEPRECATED_MACRO_IN_2_44
#define GOBJECT_DEPRECATED_MACRO_IN_2_46
#define GOBJECT_DEPRECATED_MACRO_IN_2_48
#define GOBJECT_DEPRECATED_MACRO_IN_2_50
#define GOBJECT_DEPRECATED_MACRO_IN_2_52
#define GOBJECT_DEPRECATED_MACRO_IN_2_54
#define GOBJECT_DEPRECATED_MACRO_IN_2_56
#define GOBJECT_DEPRECATED_MACRO_IN_2_58
#define GOBJECT_DEPRECATED_MACRO_IN_2_60
#define GOBJECT_DEPRECATED_MACRO_IN_2_62
#define GOBJECT_DEPRECATED_MACRO_IN_2_64
#define GOBJECT_DEPRECATED_MACRO_IN_2_66
#define GOBJECT_DEPRECATED_MACRO_IN_2_68
#define GOBJECT_DEPRECATED_MACRO_IN_2_70
#define GOBJECT_DEPRECATED_MACRO_IN_2_72
#define GOBJECT_DEPRECATED_MACRO_IN_2_74
#define GOBJECT_DEPRECATED_MACRO_IN_2_76
#define GOBJECT_DEPRECATED_MACRO_IN_2_78
#define GOBJECT_DEPRECATED_MACRO_IN_2_80
#define GOBJECT_DEPRECATED_MACRO_IN_2_82
#define GOBJECT_DEPRECATED_MACRO_IN_2_84
#define GOBJECT_DEPRECATED_MACRO_IN_2_86

/* Deprecated macro markers with parameters - empty for WASM build */
#define GOBJECT_DEPRECATED_MACRO_IN_2_26_FOR(f)
#define GOBJECT_DEPRECATED_MACRO_IN_2_28_FOR(f)
#define GOBJECT_DEPRECATED_MACRO_IN_2_30_FOR(f)
#define GOBJECT_DEPRECATED_MACRO_IN_2_32_FOR(f)
#define GOBJECT_DEPRECATED_MACRO_IN_2_34_FOR(f)
#define GOBJECT_DEPRECATED_MACRO_IN_2_36_FOR(f)
#define GOBJECT_DEPRECATED_MACRO_IN_2_38_FOR(f)
#define GOBJECT_DEPRECATED_MACRO_IN_2_40_FOR(f)
#define GOBJECT_DEPRECATED_MACRO_IN_2_42_FOR(f)
#define GOBJECT_DEPRECATED_MACRO_IN_2_44_FOR(f)
#define GOBJECT_DEPRECATED_MACRO_IN_2_46_FOR(f)
#define GOBJECT_DEPRECATED_MACRO_IN_2_48_FOR(f)
#define GOBJECT_DEPRECATED_MACRO_IN_2_50_FOR(f)
#define GOBJECT_DEPRECATED_MACRO_IN_2_52_FOR(f)
#define GOBJECT_DEPRECATED_MACRO_IN_2_54_FOR(f)
#define GOBJECT_DEPRECATED_MACRO_IN_2_56_FOR(f)
#define GOBJECT_DEPRECATED_MACRO_IN_2_58_FOR(f)
#define GOBJECT_DEPRECATED_MACRO_IN_2_60_FOR(f)
#define GOBJECT_DEPRECATED_MACRO_IN_2_62_FOR(f)
#define GOBJECT_DEPRECATED_MACRO_IN_2_64_FOR(f)
#define GOBJECT_DEPRECATED_MACRO_IN_2_66_FOR(f)
#define GOBJECT_DEPRECATED_MACRO_IN_2_68_FOR(f)
#define GOBJECT_DEPRECATED_MACRO_IN_2_70_FOR(f)
#define GOBJECT_DEPRECATED_MACRO_IN_2_72_FOR(f)
#define GOBJECT_DEPRECATED_MACRO_IN_2_74_FOR(f)
#define GOBJECT_DEPRECATED_MACRO_IN_2_76_FOR(f)
#define GOBJECT_DEPRECATED_MACRO_IN_2_78_FOR(f)
#define GOBJECT_DEPRECATED_MACRO_IN_2_80_FOR(f)
#define GOBJECT_DEPRECATED_MACRO_IN_2_82_FOR(f)
#define GOBJECT_DEPRECATED_MACRO_IN_2_84_FOR(f)
#define GOBJECT_DEPRECATED_MACRO_IN_2_86_FOR(f)

/* Additional missing macros */
#define GOBJECT_VAR extern
#endif

#endif /* __GOBJECT_VISIBILITY_H__ */