/* GLIB - Library of useful routines for C programming
 * Copyright (C) 1995-1997  Peter Mattis, Spencer Kimball and Josh MacDonald
 *
 * SPDX-License-Identifier: LGPL-2.1-or-later
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, see <http://www.gnu.org/licenses/>.
 */

#ifndef __GLIB_VISIBILITY_H__
#define __GLIB_VISIBILITY_H__

#if !defined(__GLIB_H_INSIDE__) && !defined(GLIB_COMPILATION)
#error "Only <glib.h> can be included directly."
#endif

/* Symbol visibility and export macros for WASM */

/* For WASM builds, we don't need complex visibility controls */
#ifdef GLIB_STATIC_COMPILATION
#define GLIB_AVAILABLE_IN_ALL
#define GLIB_AVAILABLE_IN_2_26
#define GLIB_AVAILABLE_IN_2_28
#define GLIB_AVAILABLE_IN_2_30
#define GLIB_AVAILABLE_IN_2_32
#define GLIB_AVAILABLE_IN_2_34
#define GLIB_AVAILABLE_IN_2_36
#define GLIB_AVAILABLE_IN_2_38
#define GLIB_AVAILABLE_IN_2_40
#define GLIB_AVAILABLE_IN_2_42
#define GLIB_AVAILABLE_IN_2_44
#define GLIB_AVAILABLE_IN_2_46
#define GLIB_AVAILABLE_IN_2_48
#define GLIB_AVAILABLE_IN_2_50
#define GLIB_AVAILABLE_IN_2_52
#define GLIB_AVAILABLE_IN_2_54
#define GLIB_AVAILABLE_IN_2_56
#define GLIB_AVAILABLE_IN_2_58
#define GLIB_AVAILABLE_IN_2_60
#define GLIB_AVAILABLE_IN_2_62
#define GLIB_AVAILABLE_IN_2_64
#define GLIB_AVAILABLE_IN_2_66
#define GLIB_AVAILABLE_IN_2_68
#define GLIB_AVAILABLE_IN_2_70
#define GLIB_AVAILABLE_IN_2_72
#define GLIB_AVAILABLE_IN_2_74
#define GLIB_AVAILABLE_IN_2_76
#define GLIB_AVAILABLE_IN_2_78
#define GLIB_AVAILABLE_IN_2_80
#define GLIB_AVAILABLE_IN_2_82
#define GLIB_AVAILABLE_IN_2_84
#define GLIB_AVAILABLE_IN_2_86

/* Enumerator availability macros */
#define GLIB_AVAILABLE_ENUMERATOR_IN_2_26
#define GLIB_AVAILABLE_ENUMERATOR_IN_2_28
#define GLIB_AVAILABLE_ENUMERATOR_IN_2_30
#define GLIB_AVAILABLE_ENUMERATOR_IN_2_32
#define GLIB_AVAILABLE_ENUMERATOR_IN_2_34
#define GLIB_AVAILABLE_ENUMERATOR_IN_2_36
#define GLIB_AVAILABLE_ENUMERATOR_IN_2_38
#define GLIB_AVAILABLE_ENUMERATOR_IN_2_40
#define GLIB_AVAILABLE_ENUMERATOR_IN_2_42
#define GLIB_AVAILABLE_ENUMERATOR_IN_2_44
#define GLIB_AVAILABLE_ENUMERATOR_IN_2_46
#define GLIB_AVAILABLE_ENUMERATOR_IN_2_48
#define GLIB_AVAILABLE_ENUMERATOR_IN_2_50
#define GLIB_AVAILABLE_ENUMERATOR_IN_2_52
#define GLIB_AVAILABLE_ENUMERATOR_IN_2_54
#define GLIB_AVAILABLE_ENUMERATOR_IN_2_56
#define GLIB_AVAILABLE_ENUMERATOR_IN_2_58
#define GLIB_AVAILABLE_ENUMERATOR_IN_2_60
#define GLIB_AVAILABLE_ENUMERATOR_IN_2_62
#define GLIB_AVAILABLE_ENUMERATOR_IN_2_64
#define GLIB_AVAILABLE_ENUMERATOR_IN_2_66
#define GLIB_AVAILABLE_ENUMERATOR_IN_2_68
#define GLIB_AVAILABLE_ENUMERATOR_IN_2_70
#define GLIB_AVAILABLE_ENUMERATOR_IN_2_72
#define GLIB_AVAILABLE_ENUMERATOR_IN_2_74
#define GLIB_AVAILABLE_ENUMERATOR_IN_2_76
#define GLIB_AVAILABLE_ENUMERATOR_IN_2_78
#define GLIB_AVAILABLE_ENUMERATOR_IN_2_80
#define GLIB_AVAILABLE_ENUMERATOR_IN_2_82
#define GLIB_AVAILABLE_ENUMERATOR_IN_2_84
#define GLIB_AVAILABLE_ENUMERATOR_IN_2_86

/* Variable and static inline availability macros */
#define GLIB_VAR extern
#define GLIB_AVAILABLE_STATIC_INLINE_IN_2_44
#define GLIB_AVAILABLE_STATIC_INLINE_IN_2_46
#define GLIB_AVAILABLE_STATIC_INLINE_IN_2_48
#define GLIB_AVAILABLE_STATIC_INLINE_IN_2_50
#define GLIB_AVAILABLE_STATIC_INLINE_IN_2_52
#define GLIB_AVAILABLE_STATIC_INLINE_IN_2_54
#define GLIB_AVAILABLE_STATIC_INLINE_IN_2_56
#define GLIB_AVAILABLE_STATIC_INLINE_IN_2_58
#define GLIB_AVAILABLE_STATIC_INLINE_IN_2_60
#define GLIB_AVAILABLE_STATIC_INLINE_IN_2_62
#define GLIB_AVAILABLE_STATIC_INLINE_IN_2_64
#define GLIB_AVAILABLE_STATIC_INLINE_IN_2_66
#define GLIB_AVAILABLE_STATIC_INLINE_IN_2_68
#define GLIB_AVAILABLE_STATIC_INLINE_IN_2_70
#define GLIB_AVAILABLE_STATIC_INLINE_IN_2_72
#define GLIB_AVAILABLE_STATIC_INLINE_IN_2_74
#define GLIB_AVAILABLE_STATIC_INLINE_IN_2_76
#define GLIB_AVAILABLE_STATIC_INLINE_IN_2_78
#define GLIB_AVAILABLE_STATIC_INLINE_IN_2_80
#define GLIB_AVAILABLE_STATIC_INLINE_IN_2_82
#define GLIB_AVAILABLE_STATIC_INLINE_IN_2_84
#define GLIB_AVAILABLE_STATIC_INLINE_IN_2_86

/* Type availability macros */
#define GLIB_AVAILABLE_TYPE_IN_2_26
#define GLIB_AVAILABLE_TYPE_IN_2_28
#define GLIB_AVAILABLE_TYPE_IN_2_30
#define GLIB_AVAILABLE_TYPE_IN_2_32
#define GLIB_AVAILABLE_TYPE_IN_2_34
#define GLIB_AVAILABLE_TYPE_IN_2_36
#define GLIB_AVAILABLE_TYPE_IN_2_38
#define GLIB_AVAILABLE_TYPE_IN_2_40
#define GLIB_AVAILABLE_TYPE_IN_2_42
#define GLIB_AVAILABLE_TYPE_IN_2_44
#define GLIB_AVAILABLE_TYPE_IN_2_46
#define GLIB_AVAILABLE_TYPE_IN_2_48
#define GLIB_AVAILABLE_TYPE_IN_2_50
#define GLIB_AVAILABLE_TYPE_IN_2_52
#define GLIB_AVAILABLE_TYPE_IN_2_54
#define GLIB_AVAILABLE_TYPE_IN_2_56
#define GLIB_AVAILABLE_TYPE_IN_2_58
#define GLIB_AVAILABLE_TYPE_IN_2_60
#define GLIB_AVAILABLE_TYPE_IN_2_62
#define GLIB_AVAILABLE_TYPE_IN_2_64
#define GLIB_AVAILABLE_TYPE_IN_2_66
#define GLIB_AVAILABLE_TYPE_IN_2_68
#define GLIB_AVAILABLE_TYPE_IN_2_70
#define GLIB_AVAILABLE_TYPE_IN_2_72
#define GLIB_AVAILABLE_TYPE_IN_2_74
#define GLIB_AVAILABLE_TYPE_IN_2_76
#define GLIB_AVAILABLE_TYPE_IN_2_78
#define GLIB_AVAILABLE_TYPE_IN_2_80
#define GLIB_AVAILABLE_TYPE_IN_2_82
#define GLIB_AVAILABLE_TYPE_IN_2_84
#define GLIB_AVAILABLE_TYPE_IN_2_86

/* Additional macro availability */
#define GLIB_AVAILABLE_MACRO_IN_2_26
#define GLIB_AVAILABLE_MACRO_IN_2_28
#define GLIB_AVAILABLE_MACRO_IN_2_30
#define GLIB_AVAILABLE_MACRO_IN_2_32
#define GLIB_AVAILABLE_MACRO_IN_2_34
#define GLIB_AVAILABLE_MACRO_IN_2_36
#define GLIB_AVAILABLE_MACRO_IN_2_38
#define GLIB_AVAILABLE_MACRO_IN_2_40
#define GLIB_AVAILABLE_MACRO_IN_2_42
#define GLIB_AVAILABLE_MACRO_IN_2_44
#define GLIB_AVAILABLE_MACRO_IN_2_46
#define GLIB_AVAILABLE_MACRO_IN_2_48
#define GLIB_AVAILABLE_MACRO_IN_2_50
#define GLIB_AVAILABLE_MACRO_IN_2_52
#define GLIB_AVAILABLE_MACRO_IN_2_54
#define GLIB_AVAILABLE_MACRO_IN_2_56
#define GLIB_AVAILABLE_MACRO_IN_2_58
#define GLIB_AVAILABLE_MACRO_IN_2_60
#define GLIB_AVAILABLE_MACRO_IN_2_62
#define GLIB_AVAILABLE_MACRO_IN_2_64
#define GLIB_AVAILABLE_MACRO_IN_2_66
#define GLIB_AVAILABLE_MACRO_IN_2_68
#define GLIB_AVAILABLE_MACRO_IN_2_70
#define GLIB_AVAILABLE_MACRO_IN_2_72
#define GLIB_AVAILABLE_MACRO_IN_2_74
#define GLIB_AVAILABLE_MACRO_IN_2_76
#define GLIB_AVAILABLE_MACRO_IN_2_78
#define GLIB_AVAILABLE_MACRO_IN_2_80
#define GLIB_AVAILABLE_MACRO_IN_2_82
#define GLIB_AVAILABLE_MACRO_IN_2_84
#define GLIB_AVAILABLE_MACRO_IN_2_86

/* Deprecation macros - simplified for WASM */
#define GLIB_DEPRECATED
#define GLIB_DEPRECATED_FOR(f)
#define GLIB_DEPRECATED_MACRO
#define GLIB_DEPRECATED_MACRO_FOR(f)
#define GLIB_DEPRECATED_ENUMERATOR
#define GLIB_DEPRECATED_ENUMERATOR_FOR(f)

/* Deprecated enumerator version-specific macros */
#define GLIB_DEPRECATED_ENUMERATOR_IN_2_26
#define GLIB_DEPRECATED_ENUMERATOR_IN_2_26_FOR(f)
#define GLIB_DEPRECATED_ENUMERATOR_IN_2_28
#define GLIB_DEPRECATED_ENUMERATOR_IN_2_28_FOR(f)
#define GLIB_DEPRECATED_ENUMERATOR_IN_2_30
#define GLIB_DEPRECATED_ENUMERATOR_IN_2_30_FOR(f)
#define GLIB_DEPRECATED_ENUMERATOR_IN_2_32
#define GLIB_DEPRECATED_ENUMERATOR_IN_2_32_FOR(f)
#define GLIB_DEPRECATED_ENUMERATOR_IN_2_34
#define GLIB_DEPRECATED_ENUMERATOR_IN_2_34_FOR(f)
#define GLIB_DEPRECATED_ENUMERATOR_IN_2_36
#define GLIB_DEPRECATED_ENUMERATOR_IN_2_36_FOR(f)
#define GLIB_DEPRECATED_ENUMERATOR_IN_2_38
#define GLIB_DEPRECATED_ENUMERATOR_IN_2_38_FOR(f)
#define GLIB_DEPRECATED_ENUMERATOR_IN_2_40
#define GLIB_DEPRECATED_ENUMERATOR_IN_2_40_FOR(f)
#define GLIB_DEPRECATED_ENUMERATOR_IN_2_42
#define GLIB_DEPRECATED_ENUMERATOR_IN_2_42_FOR(f)
#define GLIB_DEPRECATED_ENUMERATOR_IN_2_44
#define GLIB_DEPRECATED_ENUMERATOR_IN_2_44_FOR(f)
#define GLIB_DEPRECATED_ENUMERATOR_IN_2_46
#define GLIB_DEPRECATED_ENUMERATOR_IN_2_46_FOR(f)
#define GLIB_DEPRECATED_ENUMERATOR_IN_2_48
#define GLIB_DEPRECATED_ENUMERATOR_IN_2_48_FOR(f)
#define GLIB_DEPRECATED_ENUMERATOR_IN_2_50
#define GLIB_DEPRECATED_ENUMERATOR_IN_2_50_FOR(f)
#define GLIB_DEPRECATED_ENUMERATOR_IN_2_52
#define GLIB_DEPRECATED_ENUMERATOR_IN_2_52_FOR(f)
#define GLIB_DEPRECATED_ENUMERATOR_IN_2_54
#define GLIB_DEPRECATED_ENUMERATOR_IN_2_54_FOR(f)
#define GLIB_DEPRECATED_ENUMERATOR_IN_2_56
#define GLIB_DEPRECATED_ENUMERATOR_IN_2_56_FOR(f)
#define GLIB_DEPRECATED_ENUMERATOR_IN_2_58
#define GLIB_DEPRECATED_ENUMERATOR_IN_2_58_FOR(f)
#define GLIB_DEPRECATED_ENUMERATOR_IN_2_60
#define GLIB_DEPRECATED_ENUMERATOR_IN_2_60_FOR(f)
#define GLIB_DEPRECATED_ENUMERATOR_IN_2_62
#define GLIB_DEPRECATED_ENUMERATOR_IN_2_62_FOR(f)
#define GLIB_DEPRECATED_ENUMERATOR_IN_2_64
#define GLIB_DEPRECATED_ENUMERATOR_IN_2_64_FOR(f)
#define GLIB_DEPRECATED_ENUMERATOR_IN_2_66
#define GLIB_DEPRECATED_ENUMERATOR_IN_2_66_FOR(f)
#define GLIB_DEPRECATED_ENUMERATOR_IN_2_68
#define GLIB_DEPRECATED_ENUMERATOR_IN_2_68_FOR(f)
#define GLIB_DEPRECATED_ENUMERATOR_IN_2_70
#define GLIB_DEPRECATED_ENUMERATOR_IN_2_70_FOR(f)
#define GLIB_DEPRECATED_ENUMERATOR_IN_2_72
#define GLIB_DEPRECATED_ENUMERATOR_IN_2_72_FOR(f)
#define GLIB_DEPRECATED_ENUMERATOR_IN_2_74
#define GLIB_DEPRECATED_ENUMERATOR_IN_2_74_FOR(f)
#define GLIB_DEPRECATED_ENUMERATOR_IN_2_76
#define GLIB_DEPRECATED_ENUMERATOR_IN_2_76_FOR(f)
#define GLIB_DEPRECATED_ENUMERATOR_IN_2_78
#define GLIB_DEPRECATED_ENUMERATOR_IN_2_78_FOR(f)
#define GLIB_DEPRECATED_ENUMERATOR_IN_2_80
#define GLIB_DEPRECATED_ENUMERATOR_IN_2_80_FOR(f)
#define GLIB_DEPRECATED_ENUMERATOR_IN_2_82
#define GLIB_DEPRECATED_ENUMERATOR_IN_2_82_FOR(f)
#define GLIB_DEPRECATED_ENUMERATOR_IN_2_84
#define GLIB_DEPRECATED_ENUMERATOR_IN_2_84_FOR(f)
#define GLIB_DEPRECATED_ENUMERATOR_IN_2_86
#define GLIB_DEPRECATED_ENUMERATOR_IN_2_86_FOR(f)
#define GLIB_DEPRECATED_TYPE
#define GLIB_DEPRECATED_TYPE_FOR(f)

/* Version-specific type deprecation macros */
#define GLIB_DEPRECATED_TYPE_IN_2_26
#define GLIB_DEPRECATED_TYPE_IN_2_26_FOR(f)
#define GLIB_DEPRECATED_TYPE_IN_2_28
#define GLIB_DEPRECATED_TYPE_IN_2_28_FOR(f)
#define GLIB_DEPRECATED_TYPE_IN_2_30
#define GLIB_DEPRECATED_TYPE_IN_2_30_FOR(f)
#define GLIB_DEPRECATED_TYPE_IN_2_32
#define GLIB_DEPRECATED_TYPE_IN_2_32_FOR(f)
#define GLIB_DEPRECATED_TYPE_IN_2_34
#define GLIB_DEPRECATED_TYPE_IN_2_34_FOR(f)
#define GLIB_DEPRECATED_TYPE_IN_2_36
#define GLIB_DEPRECATED_TYPE_IN_2_36_FOR(f)
#define GLIB_DEPRECATED_TYPE_IN_2_38
#define GLIB_DEPRECATED_TYPE_IN_2_38_FOR(f)
#define GLIB_DEPRECATED_TYPE_IN_2_40
#define GLIB_DEPRECATED_TYPE_IN_2_40_FOR(f)
#define GLIB_DEPRECATED_TYPE_IN_2_42
#define GLIB_DEPRECATED_TYPE_IN_2_42_FOR(f)
#define GLIB_DEPRECATED_TYPE_IN_2_44
#define GLIB_DEPRECATED_TYPE_IN_2_44_FOR(f)
#define GLIB_DEPRECATED_TYPE_IN_2_46
#define GLIB_DEPRECATED_TYPE_IN_2_46_FOR(f)
#define GLIB_DEPRECATED_TYPE_IN_2_48
#define GLIB_DEPRECATED_TYPE_IN_2_48_FOR(f)
#define GLIB_DEPRECATED_TYPE_IN_2_50
#define GLIB_DEPRECATED_TYPE_IN_2_50_FOR(f)
#define GLIB_DEPRECATED_TYPE_IN_2_52
#define GLIB_DEPRECATED_TYPE_IN_2_52_FOR(f)
#define GLIB_DEPRECATED_TYPE_IN_2_54
#define GLIB_DEPRECATED_TYPE_IN_2_54_FOR(f)
#define GLIB_DEPRECATED_TYPE_IN_2_56
#define GLIB_DEPRECATED_TYPE_IN_2_56_FOR(f)
#define GLIB_DEPRECATED_TYPE_IN_2_58
#define GLIB_DEPRECATED_TYPE_IN_2_58_FOR(f)
#define GLIB_DEPRECATED_TYPE_IN_2_60
#define GLIB_DEPRECATED_TYPE_IN_2_60_FOR(f)
#define GLIB_DEPRECATED_TYPE_IN_2_62
#define GLIB_DEPRECATED_TYPE_IN_2_62_FOR(f)
#define GLIB_DEPRECATED_TYPE_IN_2_64
#define GLIB_DEPRECATED_TYPE_IN_2_64_FOR(f)
#define GLIB_DEPRECATED_TYPE_IN_2_66
#define GLIB_DEPRECATED_TYPE_IN_2_66_FOR(f)
#define GLIB_DEPRECATED_TYPE_IN_2_68
#define GLIB_DEPRECATED_TYPE_IN_2_68_FOR(f)
#define GLIB_DEPRECATED_TYPE_IN_2_70
#define GLIB_DEPRECATED_TYPE_IN_2_70_FOR(f)
#define GLIB_DEPRECATED_TYPE_IN_2_72
#define GLIB_DEPRECATED_TYPE_IN_2_72_FOR(f)
#define GLIB_DEPRECATED_TYPE_IN_2_74
#define GLIB_DEPRECATED_TYPE_IN_2_74_FOR(f)
#define GLIB_DEPRECATED_TYPE_IN_2_76
#define GLIB_DEPRECATED_TYPE_IN_2_76_FOR(f)
#define GLIB_DEPRECATED_TYPE_IN_2_78
#define GLIB_DEPRECATED_TYPE_IN_2_78_FOR(f)
#define GLIB_DEPRECATED_TYPE_IN_2_80
#define GLIB_DEPRECATED_TYPE_IN_2_80_FOR(f)
#define GLIB_DEPRECATED_TYPE_IN_2_82
#define GLIB_DEPRECATED_TYPE_IN_2_82_FOR(f)
#define GLIB_DEPRECATED_TYPE_IN_2_84
#define GLIB_DEPRECATED_TYPE_IN_2_84_FOR(f)
#define GLIB_DEPRECATED_TYPE_IN_2_86
#define GLIB_DEPRECATED_TYPE_IN_2_86_FOR(f)

/* Unavailable/deprecated version-specific macros */
#define GLIB_UNAVAILABLE(maj, min)
#define GLIB_DEPRECATED_IN_2_26
#define GLIB_DEPRECATED_IN_2_26_FOR(f)
#define GLIB_DEPRECATED_IN_2_28
#define GLIB_DEPRECATED_IN_2_28_FOR(f)
#define GLIB_DEPRECATED_IN_2_30
#define GLIB_DEPRECATED_IN_2_30_FOR(f)
#define GLIB_DEPRECATED_IN_2_32
#define GLIB_DEPRECATED_IN_2_32_FOR(f)
#define GLIB_DEPRECATED_IN_2_34
#define GLIB_DEPRECATED_IN_2_34_FOR(f)
#define GLIB_DEPRECATED_IN_2_36
#define GLIB_DEPRECATED_IN_2_36_FOR(f)
#define GLIB_DEPRECATED_IN_2_38
#define GLIB_DEPRECATED_IN_2_38_FOR(f)
#define GLIB_DEPRECATED_IN_2_40
#define GLIB_DEPRECATED_IN_2_40_FOR(f)
#define GLIB_DEPRECATED_IN_2_42
#define GLIB_DEPRECATED_IN_2_42_FOR(f)
#define GLIB_DEPRECATED_IN_2_44
#define GLIB_DEPRECATED_IN_2_44_FOR(f)
#define GLIB_DEPRECATED_IN_2_46
#define GLIB_DEPRECATED_IN_2_46_FOR(f)
#define GLIB_DEPRECATED_IN_2_48
#define GLIB_DEPRECATED_IN_2_48_FOR(f)
#define GLIB_DEPRECATED_IN_2_50
#define GLIB_DEPRECATED_IN_2_50_FOR(f)
#define GLIB_DEPRECATED_IN_2_52
#define GLIB_DEPRECATED_IN_2_52_FOR(f)
#define GLIB_DEPRECATED_IN_2_54
#define GLIB_DEPRECATED_IN_2_54_FOR(f)
#define GLIB_DEPRECATED_IN_2_56
#define GLIB_DEPRECATED_IN_2_56_FOR(f)
#define GLIB_DEPRECATED_IN_2_58
#define GLIB_DEPRECATED_IN_2_58_FOR(f)
#define GLIB_DEPRECATED_IN_2_60
#define GLIB_DEPRECATED_IN_2_60_FOR(f)
#define GLIB_DEPRECATED_IN_2_62
#define GLIB_DEPRECATED_IN_2_62_FOR(f)
#define GLIB_DEPRECATED_IN_2_64
#define GLIB_DEPRECATED_IN_2_64_FOR(f)
#define GLIB_DEPRECATED_IN_2_66
#define GLIB_DEPRECATED_IN_2_66_FOR(f)
#define GLIB_DEPRECATED_IN_2_68
#define GLIB_DEPRECATED_IN_2_68_FOR(f)
#define GLIB_DEPRECATED_IN_2_70
#define GLIB_DEPRECATED_IN_2_70_FOR(f)
#define GLIB_DEPRECATED_IN_2_72
#define GLIB_DEPRECATED_IN_2_72_FOR(f)
#define GLIB_DEPRECATED_IN_2_74
#define GLIB_DEPRECATED_IN_2_74_FOR(f)
#define GLIB_DEPRECATED_IN_2_76
#define GLIB_DEPRECATED_IN_2_76_FOR(f)
#define GLIB_DEPRECATED_IN_2_78
#define GLIB_DEPRECATED_IN_2_78_FOR(f)
#define GLIB_DEPRECATED_IN_2_80
#define GLIB_DEPRECATED_IN_2_80_FOR(f)
#define GLIB_DEPRECATED_IN_2_82
#define GLIB_DEPRECATED_IN_2_82_FOR(f)
#define GLIB_DEPRECATED_IN_2_84
#define GLIB_DEPRECATED_IN_2_84_FOR(f)
#define GLIB_DEPRECATED_IN_2_86
#define GLIB_DEPRECATED_IN_2_86_FOR(f)

/* Macro version deprecation */
#define GLIB_DEPRECATED_MACRO_IN_2_26
#define GLIB_DEPRECATED_MACRO_IN_2_26_FOR(f)
#define GLIB_DEPRECATED_MACRO_IN_2_28
#define GLIB_DEPRECATED_MACRO_IN_2_28_FOR(f)
#define GLIB_DEPRECATED_MACRO_IN_2_30
#define GLIB_DEPRECATED_MACRO_IN_2_30_FOR(f)
#define GLIB_DEPRECATED_MACRO_IN_2_32
#define GLIB_DEPRECATED_MACRO_IN_2_32_FOR(f)
#define GLIB_DEPRECATED_MACRO_IN_2_34
#define GLIB_DEPRECATED_MACRO_IN_2_34_FOR(f)
#define GLIB_DEPRECATED_MACRO_IN_2_36
#define GLIB_DEPRECATED_MACRO_IN_2_36_FOR(f)
#define GLIB_DEPRECATED_MACRO_IN_2_38
#define GLIB_DEPRECATED_MACRO_IN_2_38_FOR(f)
#define GLIB_DEPRECATED_MACRO_IN_2_40
#define GLIB_DEPRECATED_MACRO_IN_2_40_FOR(f)
#define GLIB_DEPRECATED_MACRO_IN_2_42
#define GLIB_DEPRECATED_MACRO_IN_2_42_FOR(f)
#define GLIB_DEPRECATED_MACRO_IN_2_44
#define GLIB_DEPRECATED_MACRO_IN_2_44_FOR(f)
#define GLIB_DEPRECATED_MACRO_IN_2_46
#define GLIB_DEPRECATED_MACRO_IN_2_46_FOR(f)
#define GLIB_DEPRECATED_MACRO_IN_2_48
#define GLIB_DEPRECATED_MACRO_IN_2_48_FOR(f)
#define GLIB_DEPRECATED_MACRO_IN_2_50
#define GLIB_DEPRECATED_MACRO_IN_2_50_FOR(f)
#define GLIB_DEPRECATED_MACRO_IN_2_52
#define GLIB_DEPRECATED_MACRO_IN_2_52_FOR(f)
#define GLIB_DEPRECATED_MACRO_IN_2_54
#define GLIB_DEPRECATED_MACRO_IN_2_54_FOR(f)
#define GLIB_DEPRECATED_MACRO_IN_2_56
#define GLIB_DEPRECATED_MACRO_IN_2_56_FOR(f)
#define GLIB_DEPRECATED_MACRO_IN_2_58
#define GLIB_DEPRECATED_MACRO_IN_2_58_FOR(f)
#define GLIB_DEPRECATED_MACRO_IN_2_60
#define GLIB_DEPRECATED_MACRO_IN_2_60_FOR(f)
#define GLIB_DEPRECATED_MACRO_IN_2_62
#define GLIB_DEPRECATED_MACRO_IN_2_62_FOR(f)
#define GLIB_DEPRECATED_MACRO_IN_2_64
#define GLIB_DEPRECATED_MACRO_IN_2_64_FOR(f)
#define GLIB_DEPRECATED_MACRO_IN_2_66
#define GLIB_DEPRECATED_MACRO_IN_2_66_FOR(f)
#define GLIB_DEPRECATED_MACRO_IN_2_68
#define GLIB_DEPRECATED_MACRO_IN_2_68_FOR(f)
#define GLIB_DEPRECATED_MACRO_IN_2_70
#define GLIB_DEPRECATED_MACRO_IN_2_70_FOR(f)
#define GLIB_DEPRECATED_MACRO_IN_2_72
#define GLIB_DEPRECATED_MACRO_IN_2_72_FOR(f)
#define GLIB_DEPRECATED_MACRO_IN_2_74
#define GLIB_DEPRECATED_MACRO_IN_2_74_FOR(f)
#define GLIB_DEPRECATED_MACRO_IN_2_76
#define GLIB_DEPRECATED_MACRO_IN_2_76_FOR(f)
#define GLIB_DEPRECATED_MACRO_IN_2_78
#define GLIB_DEPRECATED_MACRO_IN_2_78_FOR(f)
#define GLIB_DEPRECATED_MACRO_IN_2_80
#define GLIB_DEPRECATED_MACRO_IN_2_80_FOR(f)
#define GLIB_DEPRECATED_MACRO_IN_2_82
#define GLIB_DEPRECATED_MACRO_IN_2_82_FOR(f)
#define GLIB_DEPRECATED_MACRO_IN_2_84
#define GLIB_DEPRECATED_MACRO_IN_2_84_FOR(f)
#define GLIB_DEPRECATED_MACRO_IN_2_86
#define GLIB_DEPRECATED_MACRO_IN_2_86_FOR(f)

#else
/* Non-static builds would use proper visibility attributes here */
#define GLIB_AVAILABLE_IN_ALL extern
#define GLIB_AVAILABLE_IN_2_26 extern
/* ... etc for all versions ... */

/* For now, just use extern for WASM */
#define GLIB_AVAILABLE_IN_2_28 extern
#define GLIB_AVAILABLE_IN_2_30 extern
#define GLIB_AVAILABLE_IN_2_32 extern
#define GLIB_AVAILABLE_IN_2_34 extern
#define GLIB_AVAILABLE_IN_2_36 extern
#define GLIB_AVAILABLE_IN_2_38 extern
#define GLIB_AVAILABLE_IN_2_40 extern
#define GLIB_AVAILABLE_IN_2_42 extern
#define GLIB_AVAILABLE_IN_2_44 extern
#define GLIB_AVAILABLE_IN_2_46 extern
#define GLIB_AVAILABLE_IN_2_48 extern
#define GLIB_AVAILABLE_IN_2_50 extern
#define GLIB_AVAILABLE_IN_2_52 extern
#define GLIB_AVAILABLE_IN_2_54 extern
#define GLIB_AVAILABLE_IN_2_56 extern
#define GLIB_AVAILABLE_IN_2_58 extern
#define GLIB_AVAILABLE_IN_2_60 extern
#define GLIB_AVAILABLE_IN_2_62 extern
#define GLIB_AVAILABLE_IN_2_64 extern
#define GLIB_AVAILABLE_IN_2_66 extern
#define GLIB_AVAILABLE_IN_2_68 extern
#define GLIB_AVAILABLE_IN_2_70 extern
#define GLIB_AVAILABLE_IN_2_72 extern
#define GLIB_AVAILABLE_IN_2_74 extern
#define GLIB_AVAILABLE_IN_2_76 extern
#define GLIB_AVAILABLE_IN_2_78 extern
#define GLIB_AVAILABLE_IN_2_80 extern
#define GLIB_AVAILABLE_IN_2_82 extern
#define GLIB_AVAILABLE_IN_2_84 extern
#define GLIB_AVAILABLE_IN_2_86 extern

/* Same deprecation macros as static case */
#define GLIB_DEPRECATED
#define GLIB_DEPRECATED_FOR(f)
/* ... etc ... */

#endif /* GLIB_STATIC_COMPILATION */

#endif /* __GLIB_VISIBILITY_H__ */